ermineapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import main_view,  signup_view
from users.views import my_recommendations_view
from transaction.views import TransactionFlowView

urlpatterns = [
    path('admin/', admin.site.urls),
    # for referral links
    path('refer/', main_view, name='main-view'),
    path('signup/', signup_view, name='signup-view'),
    path('refer/<str:ref_code>', main_view, name='main-view'),
    path('myrecs/', my_recommendations_view, name='myrecs-view'),
    path('<int:pk>/', TransactionFlowView.as_view(), name='transaction-flow'), 
    
    #other module links
    path('', include('pages.urls', namespace='pages')),
    path('users/', include('users.urls')),
    path('merchant/', include('merchant.urls')),
    path('subscriber/', include('subscriber.urls')),
    path('transaction/', include('transaction.urls')),
    path('order/', include('order.urls')),

    # path('ckeditor', include('ckeditor_uploader.urls')),    #for ckeditor image upload
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views
from order import views as order_view


app_name = 'order'

urlpatterns = [
    path('', views.StateListView.as_view(), name='state_list'),
    path('my-state/', views.StateSelfListView.as_view(), name='my-state'),
    path('<slug:slug>/', views.LgaListView.as_view(), name='lga_list'),
    path('<str:state>/<slug:slug>/', views.OrderListView.as_view(), name='order_list'),
    path('<str:state>/<str:slug>/create/', views.OrderCreateView.as_view(), name='order_create'),
    path('<str:state>/<str:lga>/<slug:slug>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('<str:state>/<str:lga>/<slug:slug>/update/', views.OrderUpdateView.as_view(), name='order_update'),
    path('<str:state>/<str:lga>/<slug:slug>/delete/', views.OrderDeleteView.as_view(), name='order_delete'),

    
]

ticket/urls.py
from django.urls import path
from . import views
from .models import views as curriculum_view


app_name = 'ticket'

urlpatterns = [
    path('', views.GroupListView.as_view(), name='group_list'),
    path('my-group/', views.GroupSelfListView.as_view(), name='my-group'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:group>/<slug:slug>/', views.TicketListView.as_view(), name='ticket_list'),
    path('<str:group>/<str:slug>/create/', views.TicketCreateView.as_view(), name='ticket_create'),
    path('<str:group>/<str:subject>/<slug:slug>/', views.TicketDetailView.as_view(), name='ticket_detail'),
    path('<str:group>/<str:subject>/<slug:slug>/update/', views.TicketUpdateView.as_view(), name='ticket_update'),
    path('<str:group>/<str:subject>/<slug:slug>/delete/', views.TicketDeleteView.as_view(), name='ticket_delete'),

    
]

order/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from .utils import generate_order_id
import os
from embed_video.fields import EmbedVideoField
from django.urls import reverse
#from ckeditor.fields import RichTextField
from django_ckeditor_5.fields import CKEditor5Field
from django.utils.html import strip_tags

# Create your models here.


class State(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(max_length=500, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Lga(models.Model):
    lga_id = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    state = models.ForeignKey(State, on_delete=models.CASCADE, related_name='subjects')
    # image = models.ImageField(upload_to=save_subject_image, blank=True, verbose_name='Subject Image')
    description = models.TextField(max_length=500, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.lga_id)
        super().save(*args, **kwargs)

    class Meta:
      verbose_name = 'Lgas'
      verbose_name_plural = 'Lgas'


class Order(models.Model):
    order_id = models.CharField(max_length=8, blank=True)
    max_amount = models.IntegerField(help_text='Enter Max Amount')
    min_amount = models.IntegerField(help_text='Enter Min Amount')
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    lga = models.ForeignKey(Lga, on_delete=models.CASCADE, related_name='lessons')
    name = models.CharField(max_length=250)
    Notes = models.FileField(upload_to='save_lesson_files', verbose_name="Notes", blank=True)
    comment = CKEditor5Field('Text', config_name='extends')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(null=True, blank=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.order_id =="":
            order_id = generate_order_id()
            self.order_id = order_id
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('order:order_list', kwargs={'slug':self.subject.slug, 'standard':self.standard.slug})

    @property
    def html_stripped(self):
       
       return strip_tags(self.comment)
    
    @property
    def merchant_commission(self):
       return self.max_amount * 0.01
    
    @property
    def company_charges(self):
       return self.merchant_commission * 0.3
            

# comment module
class Comment(models.Model):
    order_name = models.ForeignKey(Order, null=True, on_delete=models.CASCADE, related_name='comments')
    comm_name = models. CharField(max_length=100, blank=True)
    # reply = models.ForeignKey("comment", null=True, blank=True, on_delete=CASCADE, related_name='replies')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.comm_name = slugify("comment by" + "-" + str(self.author) + str(self.date_added))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.comm_name

    class Meta:
        ordering = ['-date_added']


class Reply(models.Model):
    comment_name = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    reply_body = models.TextField(max_length=500)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "reply to" + str(self.comment_name.comm_name)

order/forms.py
# from xml.etree.ElementTree import Comment
from django import forms
from .models import Order, Comment, Reply



class OrderForm(forms.ModelForm):
   
    class Meta:
        
        model = Order
        fields = ('order_id', 'name', 'comment')
        widgets = {
            'comment': forms.Textarea(attrs={'class':'form-control', 'rows':4, 'cols':70, 'placeholder':"Enter Your Comment"}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        labels = {"body":"Comment:"}

        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control', 'rows':4, 'cols':70, 'placeholder':"Enter Your Comment"}),
        }


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('reply_body',)

        widgets = {
            'reply_body': forms.Textarea(attrs={'class':'form-control', 'rows':2, 'cols':10}),
        }

order/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import(TemplateView, DetailView,
                                ListView, FormView, CreateView, 
                                UpdateView, DeleteView)
from .models import Order, State, Lga
from .forms import CommentForm, OrderForm, ReplyForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from users.models import Profile


class StateSelfListView(LoginRequiredMixin, ListView):
    context_object_name = 'state'
    model = State
    # template_name = 'curriculum/class_list.html'
    template_name = 'order/my_class.html'
 
    # Student can only view their class elearning
    def get_queryset(self):
        return State.objects.filter(name = self.request.user.profile.current_state)
        # return State.objects.filter(name = self.request.user)

# Standard list view for the admin and teachers
class StateListView(LoginRequiredMixin, ListView):
    context_object_name = 'states'
    model = State
    # template_name = 'curriculum/class_list.html'
    template_name = 'order/elearning_class.html'

    
class LgaListView(DetailView):
    context_object_name = 'states'
    model = State
    template_name = 'order/class_subjects.html'


class OrderListView(DetailView):
    context_object_name = 'lgas'
    model = Lga
    template_name = 'order/course_list.html'


class OrderDetailView(DetailView, FormView):
    context_object_name = 'lessons'
    model = Order
    template_name = 'order/lesson-detail.html'
    # for replies to lessons
    form_class = CommentForm
    second_form_class = ReplyForm
    '''
        send two forms to page
        see which one is posted
        take action on the form which is posted
    '''
    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class()
        # context['comments] = Comment.objects.filter(id=self.object.id)
        return context


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.get_form_class()
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'

        form = self.get_form(form_class)

        if form_name=='form' and form.is_valid():
            print("comment form is returned")
            return self.form_valid(form)
        elif form_name=='form2' and form.is_valid():
            print("reply form is returned")
            return self.form2_valid(form)

    def get_success_url(self):
        self.object = self.get_object()
        state = self.object.state
        lga = self.object.lga
        return reverse_lazy('order:order_detail', kwargs={'state':state.slug,
                                                            'lga':lga.slug,
                                                            'slug':self.object.slug})

    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.order_name = self.object.comments.name
        fm.order_name_id = self.object.id
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

    def form2_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm. comment_name_id = self.request.POST.get('comment.id')
        fm.save()
        return HttpResponseRedirect(self.get_success_url())
            



class OrderCreateView(CreateView):
    form_class = OrderForm
    context_object_name = 'subject'
    model = Lga
    template_name = 'order/lesson_create.html'

    def get_success_url(self):
        self.object = self.get_object()
        state = self.object.state
        return reverse_lazy('order:lesson_list',kwargs={'state':state.slug, 'slug':self.object.slug})

    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.created_by = self.request.user
        fm.state = self.object.state
        fm.lga = self.object
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

class OrderUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    fields = ('name', 'position', 'video', 'comment')
    model = Order
    template_name = 'curriculum/lesson_update_view.html'
    context_object_name = 'lessons'
    
    #function to check if user is the login user
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    #preventing other users from update other people's post
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.created_by:
            return True
        return False


class OrderDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Order
    context_object_name = 'orders'
    template_name = 'order/lesson_delete.html'

    def get_success_url(self):
        state = self.object.state
        lga = self.object.lga
        return reverse_lazy('order:lesson_list', kwargs={'state':state.slug, 'slug':lga.slug})

#preventing other users from update other people's post
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.created_by:
            return True
        return False



   

order/templates/order/class_subjects.html
{% extends 'pages/dashboard.html'%}
{% load static %}
{% block title %}<title>Schoolly - Class Subjects List </title>{% endblock title %}

{% block contentbody %}
<div class="content-body">
    <div class="container-fluid">
        <div class="row page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active"><a href=""><span style="font-size: 35px;">{{states.name}}</span></a>  E-learning</li>
                
                
            </ol>
        </div>
        <!-- row -->
        <div class="row">
            <div class="col-xl-4 col-xxl-6 col-lg-6">
                <div class="card">
                    <div class="card-header border-0 pb-0">
                        <h4 class="card-title">Subjects List</h4>
                    </div>
                    <div class="card-body">
                        <div id="DZ_W_TimeLine" class="widget-timeline dlab-scroll height370">
                            <ul class="timeline">
                                {% for lga in states.subjects.all %}
                                <li>
                                    <div class="timeline-badge primary"></div>
                                    <a class="timeline-panel text-muted" href="{% url 'order:lesson_list' slug=lga.slug standard=states.slug %}">
                                        
                                        <h6 class="mb-0">{{ lga.name }} <strong class="text-primary">#</strong>.</h6>
                                        <p><b>Description: </b>{{lga.description|truncatechars:20 }}<br /></p>
                                    </a>
                                </li>
                                
                               
                               {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Class Instruction</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text">Please follow instructions as directed by the instructor</p>
                    </div>
                    <div class="card-footer d-sm-flex justify-content-between align-items-center">
                        <div class="card-footer-link mb-4 mb-sm-0">
                            
                        </div>

                    </div>
                </div>
            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contentbody %}
{% block section%}
<section class="pop-cour">
    <div class="container com-sp pad-bot-70">
        <div class="row">
            <div class="con-title">
                <h2>List of subjects in -  <span>{{standards.name}}</span> </h2>
                <p>Use the links below to explore courses in each class.</p>
            </div>
        </div>
   

		{% for subject in standards.subjects.all %}
        <div class="row">
			
            <div class="col-md-6">
                
				
				
                <div>
                    <!--POPULAR COURSES-->
                    <div class="home-top-cour">
                        <!--POPULAR COURSES IMAGE-->
						 
						
                        <div class="col-md-3"> <img src="{% static 'demoschool/images/course/sm-1.jpg' %}" alt=""> </div>
                        <!--POPULAR COURSES: CONTENT-->
                        <div class="col-md-9 home-top-cour-desc">

	
							 								
						<h3>{{subject.name}}</h3>
								
                        <p><b>Description: </b>{{subject.description|truncatechars:75 }}<br /></p> <span class="home-top-cour-rat">100%</span>
                        
                        <div class="hom-list-share">
                                
                                <ul>
                                    <li><a href="{% url 'curriculum:lesson_list' slug=subject.slug standard=standards.slug %}">{{subject.name}}</a></li>
                                    <li><a href="course-details.html"><i class="fa fa-eye" aria-hidden="true"></i>10 Aavailable</a> </li>
                                    <li><a href="course-details.html"><i class="fa fa-share-alt" aria-hidden="true"></i> 570</a> </li>
                                </ul>
                           
							
                   
                        </div>
                    </div>
                </div>
            </div>
        </div> 
       
   
	{% endfor %}
</section>
	{% endblock section %}

order/templates/order/lesson_create.html
{% extends 'pages/dashboard.html'%}
{% load embed_video_tags %}

{% load static %}
{% block title %}<title>Schoolly Lesson Creation </title>{% endblock title %}

{% block contentbody%}
{% if user.is_authenticated and user.is_superuser or user.staffprofile %}

<div class="content-body">
    <div class="container-fluid">
        <div class="row page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active"><a href="javascript:void(0)">E-Learning</a></li>
                <li class="breadcrumb-item"><a href="javascript:void(0)">Lesson Creation Form</a></li>
            </ol>
        </div>
        <!-- row -->
        <div class="row">
            <div class="col-xl-10 col-xxl-10">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Create Lesson</h4>
                    </div>
                    <div class="card-body">
                        <div id="smartwizard" class="form-wizard order-create">
                            <ul class="nav nav-wizard">
                                <li>
                                       <p>Complete accordingly to upload your lesson</p>
                               
                            </ul>
                            <div class="tab-content">
                                <!-- <div id="wizard_Service" class="tab-pane" role="tabpanel"> -->
                                    <div class="row">
                                        <div class="col-lg-6 mb-2">
                                            <div class="mb-3">
                                                <form method="post" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                <label class="text-label form-label">Lesson ID*</label>
                                                <input type="text" name="lesson_id" maxlength="100" required id="id_lesson_id" class="form-control" placeholder="Lesson ID">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 mb-2">
                                            <div class="mb-3">
                                                <label class="text-label form-label">Lesson Name*</label>
                                                <input type="text" name="name" maxlength="250" required id="id_name" class="form-control" placeholder="Lesson Name">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 mb-2">
                                            <div class="mb-3">
                                                <label class="text-label form-label">Chapter No*</label>
                                                <input type="number" name="position" min="0" required id="id_position" class="form-control" placeholder="Chapter Number">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 mb-2">
                                            <div class="mb-3">
                                                <label class="text-label form-label">Other Information*</label>
                                                <!-- <input type="text" name="phoneNumber" class="form-control" placeholder="Other Info" required> -->
                                            </div>
                                        </div>
                                        <div class="col-lg-12 mb-3">
                                      
                                            <div class="mb-3">
                                                <label class="text-label form-label">Lesson Details*</label>
                                                <!-- <input type="text" name="comment" maxlength="250" required id="id_comment" class="form-control"> -->
                                                <textarea type="text" name="comment" maxlength="250" required id="id_comment" class="form-control" rows="4"></textarea>
                                            </div>
                                        </div>
                                        <div class="col-lg-6 mb-2">
                                        <div class=" mb-3">
                                            <label class="text-label form-label">Paste Video Link*</label>
                                                <input type=text name="video" id="id_video" class="form-control">
                                            </div>
											
                                        </div>
                                    </div>
                                    <div class="col-lg-6 mb-2">
                                        <div class="input-group mb-3">
                                            
                                            <div class="form-file">
                                                <label class="text-label form-label">Upload Lesson File</label>
                                                <input type="file" name="ppt" id="id_ppt" class="form-file-input form-control">
                                            </div>
											<span class="input-group-text">File</span>
                                        </div>
                                    </div>
                                      
                                    <div class="col-12">
                                        <button type="submit" name="" value="Submit" class="btn btn-primary mb-2">Create New Lesson</button>
                                    </div>
                                </form>
                                <hr>
                                </div>
                                                                        
                                    </div>
                                </div>                                                                                                    
                                                                       
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
                
                      {% endif %}        


{% endblock contentbody %}
{%block script%}
<!-- Required vendors -->

<script src="{% static 'portal/vendor/global/global.min.js' %}"></script>

<script src="{% static 'portal/vendor/jquery-steps/build/jquery.steps.min.js' %}"></script>
<script src="{% static 'portal/vendor/jquery-validation/jquery.validate.min.js' %}"></script>
<!-- Form validate init -->
<script src="{% static 'portal/js/plugins-init/jquery.validate-init.js' %}"></script>


<!-- Form Steps -->
<script src="{% static 'portal/vendor/jquery-smartwizard/dist/js/jquery.smartWizard.js' %}"></script>
<script src="{% static 'portalvendor/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>

<script src="{% static 'portal/js/custom.min.js' %}"></script>
<script src="{% static 'portal/js/dlabnav-init.js' %}"></script>
<script src="{% static 'portal/js/demo.js' %}"></script>
<script src="{% static 'portal/js/styleSwitcher.js' %}"></script>
<!-- <script>
    $(document).ready(function(){
        // SmartWizard initialize
        $('#smartwizard').smartWizard(); 
    });
</script> -->
{% endblock script %}
























{% block section%}
<section class="pop-cour">
   
    <div class="container com-sp pad-bot-70">
        <div class="row justify-content-center">
      
        </div>
		
        <div class="row justify-content-center">

            <div class="col-md-6">
              
               
    
                <!--Admin view the lesson, enter classroom-->
                <div>
                  <!--LESSON LIST-->
                  <div class="row justify-content-center">
                    {% comment %} <div class="pg-eve-desc pg-blog-desc"> {% endcomment %}
                    <h3>Create New Lesson</h3>
                    <p>Use the form below to create new lesson for the e-learning platform</p> 
                      
                  <div class="home-top-cour">
                    
                       <div class="col-md-12 home-top-cour-desc">                            
            
                        <form method="post" enctype="multipart/form-data">
                         
                            {% csrf_token %}


                            {{ form.as_p }}
                            <input type="submit" name="" value="Submit">
                           
                        </form>   
                                        
                          
                      </div>
                  </div>
              </div>
          </div>
      </div>
    
</section>


{% endblock section %}

order/templates/order/my_class.html
{% extends 'pages/dashboard.html' %}
{% load static %}
{% block title %}<title>Schoolly E-Learning Class List</title>{% endblock title %}

        <!--**********************************
            Content body start
        ***********************************-->
		{% block contentbody %}
        <div class="content-body">
            <div class="container-fluid">
				<div class="row page-titles">
					<ol class="breadcrumb">
						<li class="breadcrumb-item active"><a href="javascript:void(0)">E-LEARNING</a></li>
						<li class="breadcrumb-item"><a href="javascript:void(0)">My Current Class</a></li>
					</ol>
                </div>
                <!-- row -->

                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <p class="">Click on the standard / your class name to explore the subjects for the e-learning</p>
                              
                            </div>
                            
							{% if user.is_authenticated and user.profile %}
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-responsive-md">
                                        <thead>
                                            <tr>
                                                <th style="width:80px;"><strong>ID</strong></th>
                                                <th><strong>Standard Name</strong></th>
                                                <th><strong>Description</strong></th>
                                                <th><strong>STATUS</strong></th>
                                              
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
											{% for st in state %} 
                                            <tr>
												
                                                <td><strong>{{ st.id}}</strong></td>
                                                <td><a href="{% url 'order:subject_list' slug=st.slug %}"><h4>{{st.name }}</h4></a></td>
                                                <td>{{ st.description }}</td>
                                                <td>ACTIVE!</td>
                                                                                                											
                                            </tr>
											{% endfor %} 
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
					{% endif %}
                        <!-- /# card -->
                   
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
		

		{% endblock contentbody %}
        <!--**********************************
            Content body end
        ***********************************-->


       