ermineapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import main_view,  signup_view
from users.views import my_recommendations_view
from transaction.views import TransactionFlowView

urlpatterns = [
    path('admin/', admin.site.urls),
    # for referral links
    path('refer/', main_view, name='main-view'),
    path('signup/', signup_view, name='signup-view'),
    path('refer/<str:ref_code>', main_view, name='main-view'),
    path('myrecs/', my_recommendations_view, name='myrecs-view'),
    path('<int:pk>/', TransactionFlowView.as_view(), name='transaction-flow'), 
    
    #other module links
    path('', include('pages.urls', namespace='pages')),
    path('users/', include('users.urls')),
    path('merchant/', include('merchant.urls')),
    path('subscriber/', include('subscriber.urls')),
    path('transaction/', include('transaction.urls')),
    path('order/', include('order.urls')),

    # path('ckeditor', include('ckeditor_uploader.urls')),    #for ckeditor image upload
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views
from order import views as order_view


app_name = 'order'

urlpatterns = [
    path('', views.StateListView.as_view(), name='state_list'),
    path('my-state/', views.StateSelfListView.as_view(), name='my-state'),
    path('<slug:slug>/', views.LgaListView.as_view(), name='lga_list'),
    path('<str:state>/<slug:slug>/', views.OrderListView.as_view(), name='order_list'),
    path('<str:state>/<str:slug>/create/', views.OrderCreateView.as_view(), name='order_create'),
    path('<str:state>/<str:lga>/<slug:slug>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('<str:state>/<str:lga>/<slug:slug>/update/', views.OrderUpdateView.as_view(), name='order_update'),
    path('<str:state>/<str:lga>/<slug:slug>/delete/', views.OrderDeleteView.as_view(), name='order_delete'),

    
]

pages/urls.py
from django.urls import path
from pages import views as page_views


app_name ='pages'

urlpatterns = [

     path('', page_views.ermine_home, name='ermine-home'),
     path('dashboard/', page_views.dashboard, name='dashboard'),
     path('cooperative/', page_views.cooperative_page, name='cooperative'),
     path('helpcenter/', page_views.help_center, name='help-center'),
     path('lockscreen/', page_views.lockscreen, name='lock-screen'),
     path('logout/', page_views.logout, name='logout'),

     path('company_charges/', page_views.company_charges_chart, name='company-charges'),
     path('subscriber_charges/', page_views.subscriber_charges_chart, name='subscriber-charges-chart'),
     path('bank_detail/', page_views.subscriber_charges_chart, name='subscriber-charges-chart'),
     path('privacy_policy/', page_views.privacy_policy, name='privacy-policy'),
     path('referral_link/', page_views.referral_link, name='referral-link'),
     
     path('error/', page_views.error_page, name='error-page'),

]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views as users_views
from .views import UserDetailView, UserDeleteView



app_name ='users'

urlpatterns = [

     path('members_list/', users_views.members_list, name='members-list'),
     path('members_kyc_list/', users_views.members_kyc_list, name='members-kyc-list'),
     path('register/', users_views.register, name='register'),
     path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
     # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
     path('logout/', users_views.user_logout, name='logout'),
     path('profile/', users_views.profile, name="profile"),
     path('<str:id>/', UserDetailView.as_view(), name="profile-detail"),
     # path('<int:id>/update/', UserUpdateView.as_view(), name="profile-update"),
     # path('<int:id>/delete/', UserDeleteView.as_view(), name="profile-delete"),

     path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name="password_reset"),
     path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name="password_reset_done"),
     path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name="password_reset_confirm"),
     path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name="password_reset_complete"),
        

]

pages/templates/pages/apphome.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Ermine : Ermine Web Application" />
	<meta property="og:title" content="Ermine : Ermine Web Application" />
	<meta property="og:description" content="Ermine : Ermine Web Application" />
	<meta property="og:image" content="https://travl.dexignlab.com/xhtml/social-image.png" />
	<meta name="format-detection" content="telephone=no">
	
	<!-- PAGE TITLE HERE -->
	<title>Ermine App Home</title>
	
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="{% static 'pages/images/favicon.png'%}" />
    <link href="{% static 'pages/css/style.css' %}" rel="stylesheet">
    
</head>

<body class="vh-100">
    <!--*******************
		Preloader start
	********************-->
	<div id="preloader">
		<div class="lds-ripple">
			<div></div>
			<div></div>
		</div>
	</div>
	<!--*******************
		Preloader end
	********************-->
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-7">
                    <div class="form-input-content text-center error-page">
						<img src="{% static 'pages/images/logo-full.png' %}" alt="logo">
                        <h2 class="error-text fw-bold">ErmineApp</h2>						
                        <h5><i class="fa fa-exclamation-triangle text-warning"></i> Your Journey To Seameless Transactions Starts Here!</h5>
                        <p>Ensure you have read the <a href="https://ermine.ng/privacy-policy-2/"><b>policy and terms of service</b></a></p>
						<div>
                            <a class="btn btn-primary" href="{% url 'users:register' %}">Get Started</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<!--**********************************
	Scripts
***********************************-->
<!-- Required vendors -->
<script src="{% static 'pages/vendor/global/global.min.js' %}"></script>
<script src="{% static 'pages/js/custom.min.js' %}"></script>
<script src="{% static 'pages/js/dlabnav-init.js' %}"></script>
<script src="{% static 'pages/js/styleSwitcher.js' %}"></script>
</body>
</html>

pages/templates/pages/company_charges_chart.html
{% extends 'pages/dashboard.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

	
	<!-- PAGE TITLE HERE -->
    {% block title %}
	<title>Company Charges Chart</title>
    {% endblock title %}
	
	<!-- FAVICONS ICON -->
     {% block favicon %}
	<link rel="shortcut icon" type="image/png" href="images/favicon.png" />
	<link href="{% static 'pages/vendor/jquery-nice-select/css/nice-select.css' %}" rel="stylesheet">
    <link href="{% static 'pages/css/style.css' %}" rel="stylesheet">
    {% endblock favicon %}
</head>

<body>

    <!--*******************
        Preloader start
    ********************-->
   <div id="preloader">
		<div class="lds-ripple">
			<div></div>
			<div></div>
		</div>
    </div>
    <!--*******************
        Preloader end
    ********************-->


    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
       
        <!--**********************************
            Nav header end
        ***********************************-->
		
		<!--**********************************
            Chat box start
        ***********************************-->
		
		<!--**********************************
            Chat box End
        ***********************************-->

		
        <!--**********************************
            Header start
        ***********************************-->
    
                    
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
     
        <!--**********************************
            Sidebar end
        ***********************************-->

        <!--**********************************
            Content body start
        ***********************************-->
        {% block contentbody %}
        <div class="content-body">
            <div class="container-fluid">
				
				<div class="row page-titles">
					<ol class="breadcrumb">
						<li class="breadcrumb-item active"><a href="javascript:void(0)">Company</a></li>
						<li class="breadcrumb-item"><a href="javascript:void(0)">Charges Chart</a></li>
					</ol>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-sm mb-0 table-striped">
                                        <thead>
                                            
                                            <tr>
                                                <th class=" pe-3">
													<div class="form-check custom-checkbox mx-2">
														<input type="checkbox" class="form-check-input" id="checkAll">
														<label class="form-check-label" for="checkAll"></label>
													</div>
                                                </th>
                                                <th>Name</th>
                                                <th>Email</th>
                                                <th>Phone</th>
                                                <th class=" ps-5" style="min-width: 200px;">Billing Address
                                                </th>
                                                <th>Joined</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody id="customers">
                                            {% for m in allcharges %}
                                            <tr class="btn-reveal-trigger">
                                                <td class="py-2">
                                                    <div class="form-check custom-checkbox mx-2">
														<input type="checkbox" class="form-check-input" id="checkbox1">
														<label class="form-check-label" for="checkbox1"></label>
													</div>
                                                </td>
                                                <td class="py-3">
                                                    <a href="#">
                                                        <div class="media d-flex align-items-center">
                                                            <div class="avatar avatar-xl me-2">
                                                                <div class=""><img class="rounded-circle img-fluid"
                                                                        src="{% static 'pages/images/avatar/5.png' %}" width="30" alt="" />
                                                                </div>
                                                            </div>
                                                            <div class="media-body">
                                                                <h5 class="mb-0 fs--1">{{m.username}}</h5>
                                                            </div>
                                                        </div>
                                                    </a>
                                                </td>
                                                <td class="py-2"><a
                                                        href="mailto:">{{ m.email }}</a></td>
                                                <td class="py-2"> <a href="tel:2012001851">{{ m.profile.phone }}</a></td>
                                                <td class="py-2 ps-5">{{ m.profile.address }}</td>
                                                <td class="py-2">{{ m.profile.created }}</td>
                                                <td class="py-2 text-end">
                                                    <div class="dropdown"><button class="btn btn-primary tp-btn-light sharp" type="button" data-bs-toggle="dropdown"><span class="fs--1"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="18px" height="18px" viewBox="0 0 24 24" version="1.1"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><rect x="0" y="0" width="24" height="24"></rect><circle fill="#000000" cx="5" cy="12" r="2"></circle><circle fill="#000000" cx="12" cy="12" r="2"></circle><circle fill="#000000" cx="19" cy="12" r="2"></circle></g></svg></span></button>
                                                        <div class="dropdown-menu dropdown-menu-end border py-0">
                                                            <div class="py-2"><a class="dropdown-item"  href="#!">Edit</a><a class="dropdown-item text-danger" href="#!">Delete</a></div>
                                                        </div>
                                                    </div>
                                                </td>
                                              
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endblock contentbody %}
        <!--**********************************
            Content body end
        ***********************************-->


        <!--**********************************
            Footer start
        ***********************************-->
   
        <!--**********************************
            Footer end
        ***********************************-->

        <!--**********************************
           Support ticket button start
        ***********************************-->

        <!--**********************************
           Support ticket button end
        ***********************************-->


    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    <!--**********************************
        Scripts
    ***********************************-->
    {% block script %}
    <!-- Required vendors -->
    <script src="{% static 'pages/vendor/global/global.min.js' %}"></script>
    <script src="{% static 'pages/vendor/chart.js/Chart.bundle.min.js' %}"></script>
	<!-- Apex Chart -->
	<script src="{% static 'pages/vendor/apexchart/apexchart.js' %}"></script>

    <script src="{% static 'pages/vendor/highlightjs/highlight.pack.min.js' %}"></script>
    <!-- Circle progress -->

	<script src="{% static 'pages/vendor/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>

    <script src="{% static 'pages/js/custom.min.js' %}"></script>
	<script src="{% static 'pages/js/dlabnav-init.js' %}"></script>
	<script src="{% static 'pages/js/demo.js' %}"></script>
    <script src="{% static 'pages/js/styleSwitcher.js' %}"></script>
    {% endblock script %}
	
</body>
</html>

pages/templates/pages/error_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Travl : Hotel Admin Dashboard Bootstrap 5 Template" />
	<meta property="og:title" content="Travl : Hotel Admin Dashboard Bootstrap 5 Template" />
	<meta property="og:description" content="Travl : Hotel Admin Dashboard Bootstrap 5 Template" />
	<meta property="og:image" content="https://travl.dexignlab.com/xhtml/social-image.png" />
	<meta name="format-detection" content="telephone=no">
	
	<!-- PAGE TITLE HERE -->
	<title>Error Page</title>
	
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="images/favicon.png" />
    <link href="{% static 'pages/css/style.css' %}" rel="stylesheet">
    
</head>

<body class="vh-100">
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-7">
                    <div class="form-input-content text-center error-page">
                        <h1 class="error-text fw-bold">404</h1>
                        <h4><i class="fa fa-exclamation-triangle text-warning"></i> The page you were looking for is not found!</h4>
                        <p>You may have mistyped the address or the page may have moved.</p>
						<div>
                            <a class="btn btn-primary" href="./index.html">Back to Home</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<!--**********************************
	Scripts
***********************************-->
{% block script %}
<!-- Required vendors -->
<script src="{% static 'pages/vendor/global/global.min.js' %}"></script>
<script src="{% static 'pages/js/custom.min.js' %}"></script>
<script src="{% static 'pages/js/dlabnav-init.js' %}"></script>
<script src="{% static 'pages/js/styleSwitcher.js' %}"></script>
{% endblock script %}
</body>
</html>

pages/templates/pages/lockscreen.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Ermine : Ermine Web Application" />
	<meta property="og:title" content="Ermine : Ermine Web Application" />
	<meta property="og:description" content="Ermine : Ermine Web Application" />
	<meta property="og:image" content="https://travl.dexignlab.com/xhtml/social-image.png" />
	<meta name="format-detection" content="telephone=no">
	
	<!-- PAGE TITLE HERE -->
	<title>Ermine Dashboard-Account Locked</title>
	
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="{% static 'pages/images/favicon.png' %}" />
    <link href="{% static 'pages/css/style.css' %}" rel="stylesheet">

</head>

<body class="vh-100">
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-6">
                    <div class="authincation-content">
                        <div class="row no-gutters">
                            <div class="col-xl-12">
                                <div class="auth-form">
									<div class="text-center mb-3">
										<a href="index.html"><img src="{% static 'pages/images/logo-full.png' %}" alt=""></a>
									</div>
                                    <h4 class="text-center mb-4">Account Locked, Please Login</h4>
                                    <form action="{% url 'pages:dashboard' %}">
                                        <div class="mb-3">
                                            <label><strong>Password</strong></label>
                                            <input type="password" class="form-control" value="Password">
                                        </div>
                                        <div class="text-center">
                                            <button type="submit" class="btn btn-primary btn-block">Unlock</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #/ container -->
    <!-- Common JS -->
    <script src="{% static 'pages/vendor/global/global.min.js' %}"></script>
    <!-- Custom script -->
    <script src="{% static 'pages/vendor/dlabnav/dlabnav.min.js' %}"></script>
    <script src="{% static 'pages/js/custom.min.js' %}"></script>
    <script src="{% static 'pages/js/dlabnav-init.js' %}"></script>
	<script src="{% static 'pages/js/styleSwitcher.js' %}"></script>
</body>
</html>

pages/templates/pages/logout.html
{% extends 'pages/dashboard.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <!-- I removed the content here  -->
     
	<!-- PAGE TITLE HERE -->
	<title>Ermine Dashboard-Logout</title>
	
	<!-- FAVICONS ICON -->
     {% block favicon %}
	<link rel="shortcut icon" type="image/png" href="{% static 'pages/images/favicon.png' %}" />
    <link href="{% static 'pages/css/style.css' %}" rel="stylesheet">
    {% endblock favicon %}
</head>
{% block mainwrapper %}
{% endblock mainwrapper %}

{% block navheader %}
{% endblock navheader %}

{% block chatbox %}
{% endblock chatbox %}

{% block header %}
{% endblock header %}

{% block sidebar %}
{% endblock sidebar %}

{% block contentbody %}
<body class="vh-100">
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-6">
                    <div class="authincation-content">
                        <div class="row no-gutters">
                            <div class="col-xl-12">
                                <div class="auth-form">
									<div class="text-center mb-3">
										<a href="index.html"><img src="{% static 'pages/images/logo-full.png' %}" alt=""></a>
									</div>
                                    <h3 class="text-center mb-4">You are logged Out!</h3>
                                    
                                        <div class="mb-3 text-center">
                                            <label><strong>You can log In Again or Go Back To Home Page </strong></label>
                                            <!-- <input type="password " class="form-control" value="Password"> -->
                                        </div>
                                        <div class="text-center">
                                           <a href="{% url 'users:login' %}"> <button type="" class="btn btn-primary btn-block">Login Again</button></a>
                                        </div>
                                        <div class="new-account mt-3">
                                            <p>Back To: <a class="text-primary" href="https://ermine.ng">Home Page</a></p>
                                        </div>
                                  </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock contentbody %}
    <!-- #/ container -->
    <!-- Common JS -->

    {% block footer %}
    {% endblock footer %}
    

     {% block script %}
    <script src="{% static 'pages/vendor/global/global.min.js' %}"></script>
    <!-- Custom script -->
    <script src="{% static 'pages/vendor/dlabnav/dlabnav.min.js' %}"></script>
    <script src="{% static 'pages/js/custom.min.js' %}"></script>
    <script src="{% static 'pages/js/dlabnav-init.js' %}"></script>
	<script src="{% static 'pages/js/styleSwitcher.js' %}"></script>
    {% endblock script %}
</body>
</html>