ermineapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import main_view,  signup_view
from users.views import my_recommendations_view
from transaction.views import TransactionFlowView

urlpatterns = [
    path('admin/', admin.site.urls),
    # for referral links
    path('refer/', main_view, name='main-view'),
    path('signup/', signup_view, name='signup-view'),
    path('refer/<str:ref_code>', main_view, name='main-view'),
    path('myrecs/', my_recommendations_view, name='myrecs-view'),
    path('<int:pk>/', TransactionFlowView.as_view(), name='transaction-flow'), 
    
    #other module links
    path('', include('pages.urls', namespace='pages')),
    path('users/', include('users.urls')),
    path('merchant/', include('merchant.urls')),
    path('subscriber/', include('subscriber.urls')),
    path('transaction/', include('transaction.urls')),
    path('order/', include('order.urls')),

    # path('ckeditor', include('ckeditor_uploader.urls')),    #for ckeditor image upload
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views
from order import views as order_view


app_name = 'order'

urlpatterns = [
    path('', views.StateListView.as_view(), name='state_list'),
    path('my-state/', views.StateSelfListView.as_view(), name='my-state'),
    path('<slug:slug>/', views.LgaListView.as_view(), name='lga_list'),
    path('<str:state>/<slug:slug>/', views.OrderListView.as_view(), name='order_list'),
    path('<str:state>/<str:slug>/create/', views.OrderCreateView.as_view(), name='order_create'),
    path('<str:state>/<str:lga>/<slug:slug>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('<str:state>/<str:lga>/<slug:slug>/update/', views.OrderUpdateView.as_view(), name='order_update'),
    path('<str:state>/<str:lga>/<slug:slug>/delete/', views.OrderDeleteView.as_view(), name='order_delete'),

    
]

ticket/urls.py
from django.urls import path
from . import views
from .models import views as curriculum_view


app_name = 'ticket'

urlpatterns = [
    path('', views.GroupListView.as_view(), name='group_list'),
    path('my-group/', views.GroupSelfListView.as_view(), name='my-group'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:group>/<slug:slug>/', views.TicketListView.as_view(), name='ticket_list'),
    path('<str:group>/<str:slug>/create/', views.TicketCreateView.as_view(), name='ticket_create'),
    path('<str:group>/<str:subject>/<slug:slug>/', views.TicketDetailView.as_view(), name='ticket_detail'),
    path('<str:group>/<str:subject>/<slug:slug>/update/', views.TicketUpdateView.as_view(), name='ticket_update'),
    path('<str:group>/<str:subject>/<slug:slug>/delete/', views.TicketDeleteView.as_view(), name='ticket_delete'),

    
]

ticket/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from .utils import generate_ticket_id
import os
from embed_video.fields import EmbedVideoField
from django.urls import reverse
#from ckeditor.fields import RichTextField
from django_ckeditor_5.fields import CKEditor5Field
from django.utils.html import strip_tags

# Create your models here.


class Group(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(max_length=500, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Subject(models.Model):
    subject_id = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='groups')
    description = models.TextField(max_length=500, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.subject_id)
        super().save(*args, **kwargs)

    class Meta:
      verbose_name = 'Subjects'
      verbose_name_plural = 'Subjects'


def save_ticket_files(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get file name
    if instance.lesson_id:
        filename = 'lesson_files/{}.{}'.format(instance.ticket_id,instance.ticket_id, ext)
        if os.path.exists(filename):
            new_name = str(instance.lesson_id) + str('1')
            filename = 'lesson_images/{}/{}.{}'.format(instance.lesson_id,new_name, ext)
    
    return os.path.join(upload_to, filename)


class Ticket(models.Model):
    ticket_id = models.CharField(max_length=6, blank=True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='tickets')
    name = models.CharField(max_length=250)
    Notes = models.FileField(upload_to='save_lesson_files', verbose_name="Notes", blank=True)
    comment = CKEditor5Field('Text', config_name='extends')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(null=True, blank=True)

    class Meta:
        ordering = ['ticket_id']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.ticket_id =="":
            ticket_id = generate_ticket_id()
            self.code = ticket_id
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('ticket:lesson_list', kwargs={'slug':self.subject.slug, 'group':self.group.slug})

    @property
    def html_stripped(self):
       
       return strip_tags(self.comment)
            

# comment module
class Comment(models.Model):
    ticket_name = models.ForeignKey(Ticket, null=True, on_delete=models.CASCADE, related_name='comments')
    comm_name = models. CharField(max_length=100, blank=True)
    author_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_author')
    body = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.comm_name = slugify("comment by" + "-" + str(self.author_by) + str(self.date_added))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.comm_name

    class Meta:
        ordering = ['-date_added']


class Reply(models.Model):
    comment_name = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    reply_body = models.TextField(max_length=500)
    author_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reply_author')
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "reply to" + str(self.comment_name.comm_name)

ticket/forms.py
# from xml.etree.ElementTree import Comment
from django import forms
from .models import Ticket, Comment, Reply



class TicketForm(forms.ModelForm):
   
    class Meta:
        
        model = Ticket
        fields = ('ticket_id', 'name', 'comment')
        widgets = {
            'comment': forms.Textarea(attrs={'class':'form-control', 'rows':4, 'cols':70, 'placeholder':"Enter Your Comment"}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        labels = {"body":"Comment:"}

        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control', 'rows':4, 'cols':70, 'placeholder':"Enter Your Comment"}),
        }


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('reply_body',)

        widgets = {
            'reply_body': forms.Textarea(attrs={'class':'form-control', 'rows':2, 'cols':10}),
        }

ticket/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import(TemplateView, DetailView,
                                ListView, FormView, CreateView, 
                                UpdateView, DeleteView)
from .models import Ticket, save_lesson_files, Group, Subject
from .forms import CommentForm, TicketForm, ReplyForm, 
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
# from students.models import StudentDetail


class GroupSelfListView(LoginRequiredMixin, ListView):
    context_object_name = 'groups'
    model = Group
    template_name = 'ticket/my_class.html'
 
    # Student can only view their class elearning
    def get_queryset(self):
        return Group.objects.filter(name = self.request.user.profile)

# Standard list view for the admin and teachers
class GroupListView(LoginRequiredMixin, ListView):
    context_object_name = 'groups'
    model = Group
    # template_name = 'curriculum/class_list.html'
    template_name = 'ticket/elearning_class.html'

    
class SubjectListView(DetailView):
    context_object_name = 'groups'
    model = Group
    template_name = 'ticket/class_subjects.html'


class TicketListView(DetailView):
    context_object_name = 'subjects'
    model = Subject
    template_name = 'ticket/course_list.html'


class TicketDetailView(DetailView, FormView):
    context_object_name = 'tickets'
    model = Ticket
    template_name = 'ticket/lesson-detail.html'
    # for replies to lessons
    form_class = CommentForm
    second_form_class = ReplyForm
    '''
        send two forms to page
        see which one is posted
        take action on the form which is posted
    '''
    def get_context_data(self, **kwargs):
        context = super(TicketDetailView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class()
        return context


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.get_form_class()
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'

        form = self.get_form(form_class)

        if form_name=='form' and form.is_valid():
            print("comment form is returned")
            return self.form_valid(form)
        elif form_name=='form2' and form.is_valid():
            print("reply form is returned")
            return self.form2_valid(form)

    def get_success_url(self):
        self.object = self.get_object()
        group = self.object.group
        subject = self.object.subject
        return reverse_lazy('ticket:ticket_detail', kwargs={'group':group.slug,
                                                            'subject':subject.slug,
                                                            'slug':self.object.slug})

    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.ticket_name = self.object.comments.name
        fm.ticket_name_id = self.object.id
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

    def form2_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.comment_name_id = self.request.POST.get('comment.id')
        fm.save()
        return HttpResponseRedirect(self.get_success_url())
            

class TicketCreateView(CreateView):
    form_class = TicketForm
    context_object_name = 'subject'
    model = Subject
    template_name = 'ticket/lesson_create.html'

    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.standard
        return reverse_lazy('ticket:lesson_list',kwargs={'group':standard.slug, 'slug':self.object.slug})

    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.created_by = self.request.user
        fm.group = self.object.group
        fm.subject = self.object
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

class TicketUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    fields = ('name', 'comment')
    model = Ticket
    template_name = 'ticket/lesson_update_view.html'
    context_object_name = 'tickets'
    
    #function to check if user is the login user
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    #preventing other users from update other people's post
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.created_by:
            return True
        return False


class TicketDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Ticket
    context_object_name = 'tickets'
    template_name = 'ticket/lesson_delete.html'

    def get_success_url(self):
        group = self.object.group
        subject = self.object.subject
        return reverse_lazy('ticket:ticket_list', kwargs={'group':group.slug, 'slug':subject.slug})

#preventing other users from update other people's post
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.created_by:
            return True
        return False

ticket/templates/ticket/ticket-detail.html
{% extends 'pages/dashboard.html'%}
{% load static %}
{% load embed_video_tags %}

{% block title %}<title>Ticket Detail </title>{% endblock title%}

{% block content_body %}

<div class="content-body">
	<div class="container-fluid">
		
		<div class="row page-titles">
			<ol class="breadcrumb">
				<li class="breadcrumb-item active"><a href="javascript:void(0)">{{ tickets.subject }}</a></li>
				<li class="breadcrumb-item"><a href="javascript:void(0)">Topic :  {{ tickets.name }}</b><span> - Class : {{ tickets.group }}</span></a></li>
			</ol>
		</div>
		
		<!-- row -->
		<div class="row">
			<div class="col-lg-12">
				<div class="card">
					<div class="card-body">
						<div class="email-left-box generic-width px-0 mb-5">
							<div class="p-0">
								{% if user.is_authenticated and user.is_superuser %}
								
								<!-- <a href="email-compose.html" class="btn btn-primary btn-block">Compose</a> -->
								<p>Use the buttons below to update or delete lessons</p>
								<p><a href="{% url 'ticket:ticket_update' group=tickets.group.slug subject=tickets.subject.slug slug=tickets.slug %}" class="btn btn-info">Update Lesson</a><br></p>
								<p><a href="{% url 'ticket:ticket_delete' group=tickets.group.slug subject=tickets.subject.slug slug=tickets.slug %}" class="btn btn-secondary">Delete Lesson</a></p>
								{% else %}
								<p><a href="#">Teacher's Contact</a><br></p>

								{% endif %}
							
							</div>

						</div>
						<div class="email-right-box ms-0 ms-sm-4 ms-sm-0">
							<div class="row">
						
										<div class="read-content">
											<div class="media pt-3 d-sm-flex d-block justify-content-between">
												<div class="clearfix mb-3 d-flex">
													<div class="media-body me-2">
														<h5 class="text-primary mb-0 mt-1"><span style="color:black">Created by: </span> {{ tickets.created_by}}</h5>
														<h5 class="text-primary mb-0 mt-1"><span style="color:black">Created on: </span> {{ tickets.created_at}}</h5>
														
													</div>
												</div>
												<div class="clearfix mb-3">
													<a href="javascript:void()" class="btn btn-primary px-3 my-1 light me-2"><i class="fa fa-reply"></i> </a>
													<a href="javascript:void()" class="btn btn-primary px-3 my-1 light me-2"><i class="fas fa-arrow-right"></i> </a>
													<a href="javascript:void()" class="btn btn-primary px-3 my-1 light me-2"><i class="fa fa-trash"></i></a>
												</div>
											</div>
											<hr>
											<div class="media mb-2 mt-3">
												
												<div class="media-body">
													<h2 class="mb-4">Ticket Details:</h2>																								
													
													<p class="read-content-email">
														Watch Lesson video here..</p>
												</div>
											</div>
											<div>
																					
												<!-- make sure the video link looks like this https://www.youtube.com/embed/dGF1x14QNGA -->
												<iframe width="620" height="345" 									
												src="" frameborder="0" allowfullscreen>  
												                     
												
												</iframe>                     
												
											</div>
											
											<div class="read-content-body">
												<p class="mb-2"><strong>Teacher's Highlights:</strong><br> </p>
												{{ tickets.comment | safe }}
												<p class="mb-2"></p>
																								
												<hr>
											</div>
											<div class="read-content-attachment">
												<h6><i class="fa fa-download mb-2"></i> Download or view Lesson Attachments</h6>
													<div class="row attachment">
													<div class="col-auto">
														{% if lessons.ppt %}
														<a href=""  download="" class="text-muted"><span style="color:red;"></span>Download Lesson</span></a>
													</div>
													<div class="col-auto" >
														<a href="" class="text-muted"><span style="color:red;">Read Lesson</span></a>
													</div>
													{% endif %}
												</div>
											</div>
											<hr>
											<div class="mb-3 pt-3">
												
													<h6>Comment Area</h6>
													<div class="">
														
														<h6>Post your comment or question below:</h6>
												<form method="post">
												<div class="">
												{% csrf_token %}
												{{form.as_p}}
												<input type="submit" name="form" value="Add Comment" class="btn btn-primary btn-sm">
												</div>
												</form>
												
												{% for comment in lessons.comments.all %}
												<h4>{{comment.author}}<small><i>Posted on {{comment.date_added}}</i></small></h4>
												<p>{{comment.body}}</p>
												{% for reply in comment.replies.all %}
												<h5>{{reply.author}}<small><i>Posted on {{reply.date_added}}</i></small></h5>
												<p>{{reply.reply_body}}</p>
												
												{% endfor %}
												<!-- form to post reply -->
												
												
												<form method="post">
												
												<input type="hidden", name="comment.id" value="{{comment.id}}">
												<input type="hidden", name="comment.comm_name" value="{{comment.comm_name}}">
												{% csrf_token %}
												{{form2.as_p}}
												<input type="submit" name="form2" value="Add Reply" class="btn btn-warning btn-sm">
												
												</form>
												</div>
												</div>
												
												
												{% endfor %}

								</div>
								</div>
								
							</div>
						</div>
					</div>  
				</div>

{% endblock content_body %}

ticket/templates/ticket/ticket_create.html
{% extends 'pages/dashboard.html'%}
{% load embed_video_tags %}
{% load static %}

{% block title %}<title>Ermine Ticket Creation </title>{% endblock title %}

{% block contentbody%}
{% if user.is_authenticated and user.is_superuser or user.staffprofile %}

<div class="content-body">
    <div class="container-fluid">
        <div class="row page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Ermine</a></li>
                <li class="breadcrumb-item"><a href="javascript:void(0)">Ticket Creation Form</a></li>
            </ol>
        </div>
        <!-- row -->
        <div class="row">
            <div class="col-xl-10 col-xxl-10">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Create Ticket</h4>
                    </div>
                    <div class="card-body">
                        <div id="smartwizard" class="form-wizard order-create">
                            <ul class="nav nav-wizard">
                                <li>
                                       <p>Complete accordingly to upload your ticket</p>
                               
                            </ul>
                            <div class="tab-content">
                                <!-- <div id="wizard_Service" class="tab-pane" role="tabpanel"> -->
                                    <div class="row">
                                        <div class="col-lg-6 mb-2">
                                            <div class="mb-3">
                                                <form method="post" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                <label class="text-label form-label">Ticket ID*</label>
                                                <input type="text" name="ticket_id" maxlength="100" required id="id_lesson_id" class="form-control" placeholder="Ticket ID">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 mb-2">
                                            <div class="mb-3">
                                                <label class="text-label form-label">Ticket Name*</label>
                                                <input type="text" name="name" maxlength="250" required id="id_name" class="form-control" placeholder="Ticket Name">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 mb-2">
                                           
                                        </div>
                                        <div class="col-lg-6 mb-2">
                                            <div class="mb-3">
                                                <label class="text-label form-label">Other Information*</label>
                                                <!-- <input type="text" name="phoneNumber" class="form-control" placeholder="Other Info" required> -->
                                            </div>
                                        </div>
                                        <div class="col-lg-12 mb-3">
                                      
                                            <div class="mb-3">
                                                <label class="text-label form-label">Ticket Details*</label>
                                                <!-- <input type="text" name="comment" maxlength="250" required id="id_comment" class="form-control"> -->
                                                <textarea type="text" name="comment" maxlength="250" required id="id_comment" class="form-control" rows="4"></textarea>
                                            </div>
                                        </div>
                                        <div class="col-lg-6 mb-2">
                                        <div class=" mb-3">
                                           
                                            </div>
											
                                        </div>
                                    </div>
                                    <div class="col-lg-6 mb-2">
                                        <div class="input-group mb-3">
                                            
                                            <div class="form-file">
                                                <label class="text-label form-label">Upload Ticket File</label>
                                                <input type="file" name="ppt" id="id_ppt" class="form-file-input form-control">
                                            </div>
											<span class="input-group-text">File</span>
                                        </div>
                                    </div>
                                      
                                    <div class="col-12">
                                        <button type="submit" name="" value="Submit" class="btn btn-primary mb-2">Create New Lesson</button>
                                    </div>
                                </form>
                                <hr>
                                </div>
                                                                        
                                    </div>
                                </div>                                                                                                    
                                                                       
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
                
                      {% endif %}        


{% endblock contentbody %}
{%block scripts %}
<!-- Required vendors -->

<script src="{% static 'pages/vendor/global/global.min.js' %}"></script>

<script src="{% static 'pages/vendor/jquery-steps/build/jquery.steps.min.js' %}"></script>
<script src="{% static 'pages/vendor/jquery-validation/jquery.validate.min.js' %}"></script>
<!-- Form validate init -->
<script src="{% static 'pages/js/plugins-init/jquery.validate-init.js' %}"></script>


<!-- Form Steps -->
<script src="{% static 'pages/vendor/jquery-smartwizard/dist/js/jquery.smartWizard.js' %}"></script>
<script src="{% static 'pages/vendor/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>

<script src="{% static 'pages/js/custom.min.js' %}"></script>
<script src="{% static 'pages/js/dlabnav-init.js' %}"></script>
<script src="{% static 'pages/js/demo.js' %}"></script>
<script src="{% static 'pages/js/styleSwitcher.js' %}"></script>
<!-- <script>
    $(document).ready(function(){
        // SmartWizard initialize
        $('#smartwizard').smartWizard(); 
    });
</script> -->
{% endblock script %}
























{% block section%}
<section class="pop-cour">
   
    <div class="container com-sp pad-bot-70">
        <div class="row justify-content-center">
      
        </div>
		
        <div class="row justify-content-center">

            <div class="col-md-6">
              
               
    
                <!--Admin view the lesson, enter classroom-->
                <div>
                  <!--LESSON LIST-->
                  <div class="row justify-content-center">
                    {% comment %} <div class="pg-eve-desc pg-blog-desc"> {% endcomment %}
                    <h3>Create New Lesson</h3>
                    <p>Use the form below to create new lesson for the e-learning platform</p> 
                      
                  <div class="home-top-cour">
                    
                       <div class="col-md-12 home-top-cour-desc">                            
            
                        <form method="post" enctype="multipart/form-data">
                         
                            {% csrf_token %}


                            {{ form.as_p }}
                            <input type="submit" name="" value="Submit">
                           
                        </form>   
                                        
                          
                      </div>
                  </div>
              </div>
          </div>
      </div>
    
</section>


{% endblock section %}

ticket/templates/ticket/ticket_delete.html
{% extends 'portal/portal-home.html' %}
{% load static %}
{% block title %}<title> Delete Ticket </title>{% endblock title%}

{% block content_body %}
{% if user.is_authenticated and user.is_superuser  %}
    </div>

    <body class="vh-100">    
        <div class="authincation h-100">
            <div class="container h-100">
                <div class="row justify-content-center h-100 align-items-center">
                    <div class="col-md-5">
                        <div class="form-input-content text-center error-page">
                            <h2 class="error-text fw-bold">Oops!</h2>
                            <h3>Are you sure you want to delete this TICKET?<br>
                                TICKET:<span style="color:red">"{{ object.name }}"</span></h3>
                            <form method="post">
                                {% csrf_token %}
                           
                         
                                <button class="btn btn-danger" type="submit">Delete Ticket</button>
                                </form>
                        
                            <p>Note: You cannot reverse the delete!</p> 
                            <div>
                                <button class="btn btn-info"><a href="{% url 'ticket:group_list'  %}">No! Cancel</a></button>
                            </div>	
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}

    {% endblock content_body %}


    {% block scripts %}
    <script src="{% static 'pages/vendor/global/global.min.js' %}"></script>
    <script src="{% static 'pages/js/custom.min.js' %}"></script>
    <script src="{% static 'pages/js/dlabnav-init.js' %}"></script>
    <script src="{% static 'pages/js/styleSwitcher.js' %}"></script>
    {% endblock scripts %}