ermineapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import main_view,  signup_view
from users.views import my_recommendations_view
from transaction.views import TransactionFlowView

urlpatterns = [
    path('admin/', admin.site.urls),
    # for referral links
    path('refer/', main_view, name='main-view'),
    path('signup/', signup_view, name='signup-view'),
    path('refer/<str:ref_code>', main_view, name='main-view'),
    path('myrecs/', my_recommendations_view, name='myrecs-view'),
    path('<int:pk>/', TransactionFlowView.as_view(), name='transaction-flow'), 
    
    #other module links
    path('', include('pages.urls', namespace='pages')),
    path('users/', include('users.urls')),
    path('merchant/', include('merchant.urls')),
    path('subscriber/', include('subscriber.urls')),
    path('transaction/', include('transaction.urls')),
    path('order/', include('order.urls')),

    # path('ckeditor', include('ckeditor_uploader.urls')),    #for ckeditor image upload
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views
from order import views as order_view


app_name = 'order'

urlpatterns = [
    path('', views.StateListView.as_view(), name='state_list'),
    path('my-state/', views.StateSelfListView.as_view(), name='my-state'),
    path('<slug:slug>/', views.LgaListView.as_view(), name='lga_list'),
    path('<str:state>/<slug:slug>/', views.OrderListView.as_view(), name='order_list'),
    path('<str:state>/<str:slug>/create/', views.OrderCreateView.as_view(), name='order_create'),
    path('<str:state>/<str:lga>/<slug:slug>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('<str:state>/<str:lga>/<slug:slug>/update/', views.OrderUpdateView.as_view(), name='order_update'),
    path('<str:state>/<str:lga>/<slug:slug>/delete/', views.OrderDeleteView.as_view(), name='order_delete'),

    
]

transaction/urls.py
from django.urls import path
from transaction import views as transaction_views
from .views import MerchantTransactionDetailView, MerchantTransactionCreateView, MerchantTransactUpdateView, MerchantTransactListView, MerchantChargesUpdateView, TransactionFlowView



app_name ='transaction'

urlpatterns = [

     path('history/', transaction_views.transaction_history, name='transaction-history'),
     path('status/', transaction_views.transaction_status, name='transaction-status'),
     path('company_income/', transaction_views.company_income, name='company-income'),
     path('merchant_earning/', transaction_views.merchant_earning, name='merchant-earning'),
     path('agent_earning/', transaction_views.agent_earning, name='agent-earning'),
     path('select_merchant/', transaction_views.select_merchant, name='select-merchant'),
     # Test
    #  path('set_transaction/', transaction_views.set_transaction, name='set-transaction'),
    #  path('merchant_set_transaction/', transaction_views.merchant_set_transaction, name='merchant-set-transaction'),

     # Results Detail Views
    path('transaction_list/', MerchantTransactListView.as_view(), name='transaction-list'), 
    path('<int:pk>/', MerchantTransactionDetailView.as_view(), name='transaction-detail'), 
    path('new_transaction/', MerchantTransactionCreateView.as_view(), name="transaction-create"),
    path('<int:pk>/update/', MerchantTransactUpdateView.as_view(), name='transaction-update'),

    path('<int:pk>/charges/', MerchantChargesUpdateView.as_view(), name='transaction-charges'),

    path('<int:pk>/', TransactionFlowView.as_view(), name='transaction-flow'), 
     

]

transaction/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import MerchantSetTransact, MerchantCommssion, SubscriberTransact, TransactionComplete



class MerchantTransactionUpdateForm(forms.ModelForm):
    class Meta:
        model = MerchantCommssion
        exclude = ('payment_confirm','transaction')
        

# setting of transaction
class MerchantSetTransactForm(forms.ModelForm):
   
    class Meta:
        
        model = MerchantSetTransact
        fields = ('max_amount', 'min_amount', 'prefered_method', 'current_location', 'remote_option')
        # exclude = ('max_amount','min_amount', 'prefered_method', '')
        # widgets = {
        #     'comment': forms.Textarea(attrs={'class':'form-control', 'rows':4, 'cols':70, 'placeholder':"Enter Your Comment"}),
        # }

# Comment on Transaction
class SubscriberTransactForm(forms.ModelForm):
    class Meta:
        model = SubscriberTransact
        fields = ('trans_amount', 'payment_method', 'delivery_method',)



class TransactionForm(forms.ModelForm):   
    class Meta:
        model = MerchantSetTransact
        fields = ('max_amount', 'min_amount',)
     

class CommentForm(forms.ModelForm):
    class Meta:
        model = SubscriberTransact
        fields = ('trans_amount', 'current_location',)



class ReplyForm(forms.ModelForm):
    class Meta:
        model = TransactionComplete
        fields = ('remark', 'trans_success',)

transaction/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import MerchantSetTransact, SubscriberTransact, MerchantCommssion
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import  DetailView, CreateView,  UpdateView, ListView, FormView
from .forms import MerchantSetTransactForm, MerchantTransactionUpdateForm, CommentForm, ReplyForm

# Create your views here.

def set_transaction(request):
    return render(request, 'transaction/merchant_set_transaction.html')

# I am using function base view as above instead of this
class MerchantTransactionCreateView(LoginRequiredMixin, CreateView):
    form_class = MerchantSetTransactForm
    model = MerchantSetTransact
    template_name = 'transaction/merchant_set_transaction.html'

    def get_success_url(self):
        return reverse_lazy('transaction:transaction-detail', kwargs={'pk': self.object.pk})

    
    def form_valid(self, form):
        form.instance.merchant = self.request.user
        return super().form_valid(form)
    
    # def form_valid(self, form, *args, **kwargs):
    #     self.object = self.get_object()
    #     fm = form.save(commit=False)
    #     fm.merchant = self.request.user
    #     fm.save()
    #     return HttpResponseRedirect(self.get_success_url())
    

class MerchantTransactListView(LoginRequiredMixin, ListView):
    model = MerchantSetTransact
    template_name = 'transaction/my_transaction_list.html'
    context_object_name = 'transaction'
    ordering = ['-trans_date']
    # paginate_by = 6
    # def get_context_data(self, *args, **kwargs):
    #     context=super(MerchantTransactionDetailView, self).get_context_data(*args, **kwargs)
    #     stuff = get_object_or_404(MerchantSetTransact, id=self.kwargs['pk'])
    #     # total_likes = stuff.total_likes()
    #     # context["total_likes"] = total_likes
    #     return context

#Merchant transaction detail view
class MerchantTransactionDetailView(LoginRequiredMixin, DetailView):
    model = MerchantSetTransact
    context_object_name = 'trans_detail'
    template_name = 'transaction/my_transaction_detail.html'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        new_str = self.kwargs.get('pk') or self.request.GET.get('pk') or None

        queryset = queryset.filter(pk=new_str)
        obj = queryset.get()
        return obj

class MerchantTransactUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = MerchantSetTransact
    template_name = 'transaction/transaction_update_form.html'
    fields = ['charges_amount_paid', 'comp_bank_ref', 'max_amount', 'trans_status', 'trans_remark']
    # context_object_name = 'transaction'
    # success_url = reverse_lazy('transaction:transaction-detail', str=id)
    def get_success_url(self):
        return reverse_lazy('transaction:transaction-detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.merchant = self.request.user
        return super().form_valid(form)

    def test_func(self):
        merchantsettransact = self.get_object()
        if self.request.user == merchantsettransact.merchant:
            return True
        return False

class MerchantChargesUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = MerchantSetTransact
    template_name = 'transaction/transaction_charges_form.html'
    fields = ['charges_amount_paid', 'comp_bank_ref',]
    # context_object_name = 'transaction'
    # success_url = reverse_lazy('transaction:transaction-detail', str=id)
    def get_success_url(self):
        return reverse_lazy('transaction:transaction-detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.merchant = self.request.user
        return super().form_valid(form)

    def test_func(self):
        merchantsettransact = self.get_object()
        if self.request.user == merchantsettransact.merchant:
            return True
        return False
    

# Subscriber Transact Flow
class SubscriberTransactView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = SubscriberTransact
    template_name = 'transaction/subscriber_reply_form.html'
    fields = ['charges_amount_paid', 'comp_bank_ref',]
    # context_object_name = 'transaction'
    # success_url = reverse_lazy('transaction:transaction-detail', str=id)
    def get_success_url(self):
        return reverse_lazy('transaction:transaction-detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.subscriber = self.request.user
        return super().form_valid(form)

    def test_func(self):
        merchantsettransact = self.get_object()
        if self.request.user == merchantsettransact.merchant:
            return True
        return False


# Transaction Flow view
class TransactionFlowView(DetailView, FormView):
    context_object_name = 'transaction_flow'
    model = MerchantSetTransact
    template_name = 'transaction/transaction_flow.html'
    # for replies to MerchantSetTransact
    form_class = CommentForm
    second_form_class = ReplyForm
    '''
        send two forms to page
        see which one is posted
        take action on the form which is posted
    '''
    def get_context_data(self, **kwargs):
        context = super(TransactionFlowView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class()
        # context['comments] = Comment.objects.filter(id=self.object.id)
        return context


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.get_form_class()
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'

        form = self.get_form(form_class)

        if form_name=='form' and form.is_valid():
            print("comment form is returned")
            return self.form_valid(form)
        elif form_name=='form2' and form.is_valid():
            print("reply form is returned")
            return self.form2_valid(form)

    def get_success_url(self):
        self.object = self.get_object()
        
        return reverse_lazy('transaction:transaction-flow', kwargs={'pk':self.object.pk})
                                                            

    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.subscriber = self.request.user
        fm.trans_ref = self.object.comments.name
        fm.trans_ref_id = self.object.id
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

    def form2_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.merchant = self.request.user
        fm.comment_name_id = self.request.POST.get('subscribertransact.id')
        fm.save()
        return HttpResponseRedirect(self.get_success_url())



# # @login_required
# def merchant_set_transaction(request):
#     if request.method == 'POST':
#         set_form = MerchantSetTransactionForm(request.POST, instance=request.user)
#         # commission_form = MerchantTransactionUpdateForm(request.POST, request.FILES, instance=request.user)
#         if set_form.is_valid():
#             set_form.save()            
#             messages.success(request, f'Your Transaction is sety')
#             return redirect('transaction:merchant-set-transaction')
#     else:
#         set_form = MerchantSetTransactionForm(instance=request.user)
#         # commision_form = MerchantTransactionUpdateForm(instance=request.user)

#     context = {
#         'set_form': set_form,
#         # 'commission_form': commision_form,
#     }

#     return render(request, 'transaction/merchant_set_transaction.html', context)


# @login_required
def transaction_history(request):
    transhistory = SubscriberTransact.objects.all().order_by('-trans_date')
    context = {
        'transhistory':transhistory
    }
    return render(request, 'transaction/transaction_history.html', context)

# @login_required
def transaction_status(request):
    return render(request, 'transaction/transaction_status.html')

# @login_required
def company_income(request):
    allincome = MerchantSetTransact.objects.all().order_by('-id')
    context = {
        'allincome': allincome
    }
    return render(request, 'transaction/company_income.html', context)

# @login_required
def merchant_earning(request):
    merchantearn = SubscriberTransact.objects.all().order_by('-id')
    context = {
        'merchantearn': merchantearn
    }
    return render(request, 'transaction/merchant_earning.html', context)

# @login_required
def agent_earning(request):
    return render(request, 'transaction/agent_earning.html')

# @login_required
def select_merchant(request):
    selectmerchant = MerchantSetTransact.objects.all().order_by('-id')
    context = {
        'selectmerchant': selectmerchant
    }
    return render(request, 'transaction/select_merchant.html', context)




    # Adding another model (MotorAbility to the ResultSheet)to the original model
    # def get_queryset(self):
    #     merchant_transact= super().get_queryset()
    #     merchant_transact = merchant_transact.prefetch_related("merchantsettransact")
        
    #     return merchant_transact

transaction/templates/transaction/agent_earning.html
{% extends 'pages/dashboard.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
 
	
	<!-- PAGE TITLE HERE -->
     {% block title %}
	<title>Agent Earnings</title>
    {% endblock title %}
	
	<!-- FAVICONS ICON -->
    {% block favicon %}
	<link rel="shortcut icon" type="image/png" href="images/favicon.png" />
    <!-- Datatable -->
    <link href="{% static 'pages/vendor/datatables/css/jquery.dataTables.min.css' %}" rel="stylesheet">
    <!-- Custom Stylesheet -->
	<link href="{% static 'pages/vendor/jquery-nice-select/css/nice-select.css' %}" rel="stylesheet">
    <link href="{% static 'pages/css/style.css' %}" rel="stylesheet">
    
    {% endblock favicon %}
</head>

<body>

    <!--*******************
        Preloader start
    ********************-->
   <div id="preloader">
		<div class="lds-ripple">
			<div></div>
			<div></div>
		</div>
    </div>
    <!--*******************
        Preloader end
    ********************-->


    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
		
        <!--**********************************
            Nav header end
        ***********************************-->
		
		<!--**********************************
            Chat box start
        ***********************************-->
		
		<!--**********************************
            Chat box End
        ***********************************-->


		
		
        <!--**********************************
            Header start
        ***********************************-->
       
                    
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
        
        <!--**********************************
            Sidebar end
        ***********************************-->

        <!--**********************************
            Content body start
        ***********************************-->
        {% block contentbody %}
        <div class="content-body">
            <div class="container-fluid">
<!-- 				
				<div class="row page-titles">
					<ol class="breadcrumb">
						<li class="breadcrumb-item active"><a href="javascript:void(0)">Table</a></li>
						<li class="breadcrumb-item"><a href="javascript:void(0)">Datatable</a></li>
					</ol>
                </div> -->
                <!-- row -->


					<div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Agent Commission Table</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="example4" class="display" style="min-width: 845px">
                                        <thead>
                                            <tr>
                                                <th>Transaction No</th>
                                                <th>Merchant Detail</th>
                                                <th>Subscriber Detail</th>
                                                <th>Trans. Amount </th>
												<th>Payment Mode </th>                                                
                                                <th> Earning </th>
                                                <th>Date</th>
												<th>Status </th>
                                                
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>01</td>
                                                <td>Tiger Nixon</td>
                                                <td>#54605</td>
                                                <td>Library</td>
                                                <td>Cash</td>                                                                                          
                                                <td><strong>120$</strong></td>
                                                <td>2011/04/25</td>  
                                                <td><span class="badge light badge-success">Paid</span></td>
                                                
                                            </tr>
                                            
                                           
                                        
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                            </div>
                        </div>
                    </div>
				</div>
            </div>
        </div>
        {% endblock contentbody %}
        <!--**********************************
            Content body end
        ***********************************-->


        <!--**********************************
            Footer start
        ***********************************-->
   
        <!--**********************************
            Footer end
        ***********************************-->

        <!--**********************************
           Support ticket button start
        ***********************************-->

        <!--**********************************
           Support ticket button end
        ***********************************-->

        
    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    <!--**********************************
        Scripts
    ***********************************-->
    {% block script %}
    <!-- Required vendors -->
    <script src="{% static 'pages/vendor/global/global.min.js' %}"></script>
    <script src="{% static 'pages/vendor/chart.js/Chart.bundle.min.js' %}"></script>
	<!-- Apex Chart -->
	<script src="{% static 'pages/vendor/apexchart/apexchart.js' %}"></script>
	
    <!-- Datatable -->
    <script src="{% static 'pages/vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'pages/js/plugins-init/datatables.init.js' %}"></script>

	<script src="{% static 'pages/vendor/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>

    <script src="{% static 'pages/js/custom.min.js' %}"></script>
	<script src="{% static 'pages/js/dlabnav-init.js' %}"></script>
	<script src="{% static 'pages/js/demo.js' %}"></script>
    <script src="{% static 'pages/js/styleSwitcher.js' %}"></script>
    {% endblock script %}
</body>
</html>

transaction/templates/transaction/forms.html
<form method="PORST">
    {% csrf_token %}
    {{ form.as_p }}
</form>

transaction/templates/transaction/my_transaction_detail.html
{% extends 'pages/dashboard.html'%}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  	
	<!-- PAGE TITLE HERE -->
     {% block title %}
	<title>Travl Hotel Admin Dashboard</title>
    {% endblock title %}
	
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="images/favicon.png" />
	<link href="{% static 'pages/vendor/jquery-nice-select/css/nice-select.css' %}" rel="stylesheet">
    <link href="{% static 'pages/css/style.css' %}" rel="stylesheet">

</head>

<body>

    <!--*******************
        Preloader start
    ********************-->
   <div id="preloader">
		<div class="lds-ripple">
			<div></div>
			<div></div>
		</div>
    </div>
    <!--*******************
        Preloader end
    ********************-->


    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
    
        <!--**********************************
            Nav header end
        ***********************************-->
		
		<!--**********************************
            Chat box start
        ***********************************-->
	
		<!--**********************************
            Chat box End
        ***********************************-->


		
		
        <!--**********************************
            Header start
        ***********************************-->
        
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
      
        <!--**********************************
            Sidebar end
        ***********************************-->

        <!--**********************************
            Content body start
        ***********************************-->
        {% block contentbody %}
        <div class="content-body">
            <div class="container-fluid">
				<div class="row page-titles">
					<ol class="breadcrumb">
						<li class="breadcrumb-item active"><a href="javascript:void(0)">Transaction </a></li>
						<li class="breadcrumb-item"><a href="javascript:void(0)">Detail</a></li>
					</ol>
                </div>
                <!-- row -->

                <!-- row -->
                <div class="row">
                
                    <div class="col-xl-6">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Your Transaction Details</h4>
                            </div>
                            <div class="card-body">
                                <div class="basic-list-group">
                                    <div class="list-group">
                                        <a href="javascript:void()" class="list-group-item list-group-item-action flex-column align-items-start active">
                                            <div class="d-flex w-100 justify-content-between">
                                                <h5 class="mb-3 text-white">Transaction ID: {{ trans_detail.trans_id }}</h5>
                                                <small> {{ trans_detail.trans_date }} </small>
                                            </div>
                                           
                                        <a href="javascript:void()" class="list-group-item list-group-item-action flex-column align-items-start">
                                            <div class="d-flex w-100 justify-content-between">
                                                <h5 class="mb-3">Transaction</h5><small class="text-muted">3
                                                    days ago</small>
                                            </div>
                                            <p class="mb-1">Transaction ID: {{ trans_detail.trans_id }}</p>
                                            <p class="mb-1">Maximum Amount Set: N{{ trans_detail.max_amount }}</p>
                                            <p class="mb-1">Minimum Amount Set: N{{ trans_detail.min_amount }}</p>
                                            <p class="mb-1">Your Commmission: N{{ trans_detail.merchant_commission }}</p>
                                            <p class="mb-1">{{ trans_detail.merchant }}</p>
                                            <a href="{% url 'transaction:transaction-update' trans_detail.id %}">
                                                <button class="btn btn-secondary btn-lg btn-block" type="submit">Update Transaction</button>
                                            </a>

                                           
                                        </a>
                                     </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Pay To Ermine: N{{trans_detail.company_charges}}</h4>
                            </div>
                            <div class="card-body">
                                <div class="basic-list-group">
                                    <ul class="list-group">
                                        <li class="list-group-item">You must make the statutory charges payment</li>
                                        <li class="list-group-item list-group-item-primary">- Proceed To Pay</li>
                                        <li class="list-group-item list-group-item-secondary">This is a secondary list group item</li>
                                        <li class="list-group-item list-group-item-success">This is a success list group item</li>
                                        
                                        <a href="{% url 'transaction:transaction-charges' trans_detail.id %}">
                                        <button class="btn btn-primary btn-lg btn-block" type="submit">Pay Charges To Activate Transaction</button>
                                      </a>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
              
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        {% endblock contentbody %}
        <!--**********************************
            Content body end
        ***********************************-->


        <!--**********************************
            Footer start
        ***********************************-->
     
        <!--**********************************
            Footer end
        ***********************************-->

        <!--**********************************
           Support ticket button start
        ***********************************-->

        <!--**********************************
           Support ticket button end
        ***********************************-->

        
    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    <!--**********************************
        Scripts
    ***********************************-->
    {% block script %}
    <!-- Required vendors -->
    <script src="{% static 'pages/vendor/global/global.min.js' %}"></script>
	<script src="{% static 'pages/vendor/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'pages/js/custom.min.js' %}"></script>
	<script src="{% static 'pages/js/dlabnav-init.js' %}"></script>
	<script src="{% static 'pages/js/demo.js' %}"></script>
    <script src="{% static 'pages/js/styleSwitcher.js' %}"></script>
    {% endblock script %}
</body>
</html>

transaction/templates/transaction/transaction_charges_form.html
{% extends 'pages/dashboard.html' %}
{% load crispy_forms_tags %}

{% block contentbody %}

<div class="content-body">
    <div class="container-fluid">
        <div class="row page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Merchant</a></li>
                <li class="breadcrumb-item"><a href="javascript:void(0)">Update Transaction</a></li>
            </ol>
        </div>
<div class="col-lg-8 order-lg-1">
<h4 class="mb-3">Update Transaction</h4>
<form method="POST">
<div class="row">
    <div class="mb-3">
        <!-- <form method="POST" enctype="multipart/form-data" class="needs-validation"> -->
            {% csrf_token %}
             {{ form |crispy }}
    
    </div>  											                                      

<button class="btn btn-primary btn-lg btn-block" type="submit">Update Transaction</button>
</form>
{% endblock contentbody %}